# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]

try:
	maxValue = session.defaultOdbDisplay.contourOptions.autoMaxValue
	minValue = session.defaultOdbDisplay.contourOptions.autoMinValue
except:
	maxValue = 100
	minValue = -100

neutralValue = 0
if minValue >= 0 or maxValue <= 0:
	neutralValue = round((maxValue-minValue)/2., 3)

dialogBox = RsgDialog(title='BiColor Legend', kernelModule='bicolor_legend', kernelFunction='setBiLegend', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Settings', layout='LAYOUT_FILL_X')
RsgRadioButton(p='GroupBox_1', text='Max value: Auto-compute', keyword='kw_max', default=True)
RsgHorizontalFrame(name='HFrame_2', p='GroupBox_1', layout='LAYOUT_FILL_X', pl=0, pr=0, pt=0, pb=0)
RsgRadioButton(p='HFrame_2', text='Specify:', keyword='kw_max', default=False)
RsgTextField(p='HFrame_2', fieldType='Float', ncols=15, labelText='', keyword='kw_max_value', default=str(maxValue))
RsgSeparator(p='GroupBox_1')
RsgRadioButton(p='GroupBox_1', text='Neutral value: Auto-compute', keyword='kw_neutral', default=True)
RsgHorizontalFrame(name='HFrame_3', p='GroupBox_1', layout='LAYOUT_FILL_X', pl=0, pr=0, pt=0, pb=0)
RsgRadioButton(p='HFrame_3', text='Specify:', keyword='kw_neutral', default=False)
RsgTextField(p='HFrame_3', fieldType='Float', ncols=15, labelText='', keyword='kw_neutral_value', default=str(neutralValue) )
RsgSeparator(p='GroupBox_1')
RsgRadioButton(p='GroupBox_1', text='Min value: Auto-compute', keyword='kw_min', default=True)
RsgHorizontalFrame(name='HFrame_1', p='GroupBox_1', layout='LAYOUT_FILL_X', pl=0, pr=0, pt=0, pb=0)
RsgRadioButton(p='HFrame_1', text='Specify:', keyword='kw_min', default=False)
RsgTextField(p='HFrame_1', fieldType='Float', ncols=15, labelText='', keyword='kw_min_value', default=str(minValue))
RsgSeparator(p='GroupBox_1')
RsgCheckButton(p='GroupBox_1', text='Invert legend colors', keyword='kw_invert', default=False)
RsgGroupBox(name='GroupBox_2', p='DialogBox', text='Reset', layout='LAYOUT_FILL_X')
RsgCheckButton(p='GroupBox_2', text='Reset legend to defaults', keyword='kw_reset', default=False)
dialogBox.show()